// home 

export const LOAD_CHAMPIONS = 'LOAD_CHAMPIONS';
export const CHAMPIONS_LOADED = 'CHAMPIONS_LOADED';
export const CHAMPIONS_LOADING_FAIL = 'CHAMPIONS_LOADING_FAIL';
export const CHAMPIONLIST_LOADED = 'CHAMPIONLIST_LOADED';
export const IGNORELIST_LOADED = 'IGNORELIST_LOADED';
export const LOAD_RANDOMIZER = 'LOAD_RANDOMIZER';
export const RANDOMIZER_LOADED = 'RANDOMIZER_LOADED';
export const RANDOMIZER_LOADING_FAIL = 'RANDOMIZER_LOADING_FAIL';